/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;
import clases.Conexion;
import clases.Libro;
import clases.Inventario;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author diego
 */
public class Buscador extends javax.swing.JFrame {

    Conexion conexion;
    Connection conn = null;
    

    DefaultTableModel dtm = new DefaultTableModel();
    
    public Buscador() {
        initComponents();
        
        PointerInfo pointerInfo = MouseInfo.getPointerInfo();
        GraphicsDevice gd = pointerInfo.getDevice();
        Rectangle bounds = gd.getDefaultConfiguration().getBounds();

        // Obtener las dimensiones del formulario
        int frameWidth = 400;  // Ancho del formulario
        int frameHeight = 430; // Alto del formulario

        // Calcular las coordenadas para centrar el formulario
        int x = bounds.x + (bounds.width - frameWidth) / 2;
        int y = bounds.y + (bounds.height - frameHeight) / 2;

        //this.setSize(frameWidth, frameHeight);
        this.setLocation(x, y);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        
        Funciones.CargarLogo(lbl_logo);
        
        ISBNRadio.setSelected(false);
        autorRadio.setSelected(false);
        tituloRadio.setSelected(true);
        
        String[] titulos = new String[]{"Titulo", "ISBN", "Resumen", "Precio", "Stock", "Editorial", "Categoria","Descuento","Autores"};
        dtm.setColumnIdentifiers(titulos);
        tablaBusqueda.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tituloRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        ISBNRadio = new javax.swing.JRadioButton();
        autorRadio = new javax.swing.JRadioButton();
        jButtonRegresar = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel12.setText("BUSCADOR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        tituloRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloRadio.setText("Título");
        tituloRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloRadioActionPerformed(evt);
            }
        });
        jPanel1.add(tituloRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Buscar por:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        ISBNRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ISBNRadio.setText("ISBN");
        ISBNRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNRadioActionPerformed(evt);
            }
        });
        jPanel1.add(ISBNRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        autorRadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        autorRadio.setText("Autor");
        autorRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorRadioActionPerformed(evt);
            }
        });
        jPanel1.add(autorRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jButtonRegresar.setBackground(new java.awt.Color(209, 59, 83));
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 150, 40));
        jPanel1.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 490, 30));

        buscarButton.setBackground(new java.awt.Color(209, 59, 83));
        buscarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscarButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 40));

        lbl_logo.setText("logo");
        lbl_logo.setToolTipText("");
        jPanel1.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 70));

        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "ISBN", "Resumen", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaBusqueda);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 490, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloRadioActionPerformed
        if(tituloRadio.isEnabled()){
            ISBNRadio.setSelected(false);
            autorRadio.setSelected(false);
        }
        System.out.println("Esta activado titulo");
    }//GEN-LAST:event_tituloRadioActionPerformed

    private void ISBNRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNRadioActionPerformed
        if(ISBNRadio.isEnabled()){
            autorRadio.setSelected(false);
            tituloRadio.setSelected(false);
        }
        System.out.println("Esta activado ISBN");
    }//GEN-LAST:event_ISBNRadioActionPerformed

    private void autorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorRadioActionPerformed
        if(autorRadio.isEnabled()){
            ISBNRadio.setSelected(false);
            tituloRadio.setSelected(false);
        }
        System.out.println("Esta activado autor");
    }//GEN-LAST:event_autorRadioActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        this.setVisible(false);
        new PuntoDeVenta(null).setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String input = inputSearch.getText();
        System.out.println(input);
        
        dtm.setRowCount(0);
        
        this.conexion = new Conexion();
        conn = this.conexion.establecerConexion();
        
          Inventario inv = new Inventario();
         List<Libro> listaLibros = inv.inventario();
        List<Libro> resultados = new ArrayList<>();
        
        
        
        if(tituloRadio.isSelected()){
            for (Libro libro : listaLibros) {
                if (libro.getTituloLibro().toLowerCase().contains(input.toLowerCase())) {
                resultados.add(libro);
                }
            }
        }   
        else if(ISBNRadio.isSelected()){
            for (Libro libro : listaLibros) {
                if (libro.getIsbnLibro().toLowerCase().contains(input.toLowerCase())) {
                resultados.add(libro);
                }
            }
        }
        else if(autorRadio.isSelected()){
            for (Libro libro : listaLibros) {
                if (libro.getAutores().toLowerCase().contains(input.toLowerCase())) {
                resultados.add(libro);
                }
            }
        }
        
         for (Libro libro : resultados) {
        Object[] rowData = {
            
            libro.getTituloLibro(),
           libro.getIsbnLibro(),
            libro.getResumenLibro(),
            libro.getPrecioLibro(),
            libro.getStockLibro(),
            libro.getEditorial(),
            libro.getCategoria(),
            libro.getDescuento(),
            libro.getAutores()
           
            
            
        };
        dtm.addRow(rowData);
    }
      
       if (resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
        
        
            /*
            if(conn!=null){
                try {
                    //String query = "SELECT \"estatusEmpleado\" FROM \"public\".empleado WHERE \"usuarioEmpleado\" = '" + usuario "';
                    String query = "SELECT \"tituloLibro\", \"isbnLibro\", \"resumenLibro\", \"precioLibro\", \"stockLibro\", \"editorial_id\", \"categoria_id\" FROM \"public\".\"libro\" WHERE \"tituloLibro\" = '" + input + "'";
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery(query);

                    while (rs.next()) {
                        this.tituloLibro = rs.getString("tituloLibro");
                        this.isbnLibro = rs.getString("isbnLibro");
                        this.resumenLibro = rs.getString("resumenLibro");
                        this.precioLibro = rs.getString("precioLibro");
                        this.stockLibro = rs.getString("stockLibro");
                        this.editorial_id = rs.getString("editorial_id");
                        this.categoria_id = rs.getString("categoria_id");
                    }
                    
                    rs.close();
                    stmt.close();
                    conn.close();
                    
                    if(tituloLibro.isEmpty()==false){
                        System.out.println("El campo titulo libro no esta vacio");
                        dtm.addRow(new Object[]{tituloLibro, isbnLibro, resumenLibro, precioLibro, stockLibro, editorial_id, categoria_id});
                    }else{
                        System.out.println("El campo titulo libro ESTA VACIO");
                        dtm.setRowCount(0);
                    }             
                } catch (Exception e) {
                    //System.out.println("Datos incorrectos o usuario inexistente.");
                    JOptionPane.showMessageDialog(null, "Libro no encontrado.");
                }
            }
        }
            
        if(ISBNRadio.isSelected()){
            System.out.println("Esta activado isbn y estoy buscando.");
        }
        if(autorRadio.isSelected()){
            System.out.println("Esta activado autor y estoy buscando.");
        }
            */
    }//GEN-LAST:event_buscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ISBNRadio;
    private javax.swing.JRadioButton autorRadio;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JTable tablaBusqueda;
    private javax.swing.JRadioButton tituloRadio;
    // End of variables declaration//GEN-END:variables
}
