/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTAS;

import clases.Empleado;
import clases.Vendedor;
import clases.Almacenista;
import clases.Admin;
import clases.Libro;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.Timestamp;
/**
 *
 * @author diego
 */
public class ListaDeVenta extends javax.swing.JFrame {

    Empleado empleado;
    int tipoEmp;
    double total = 0;
    double sumatoria = 0;
    
    public ListaDeVenta(Empleado empleado) {
        initComponents();
        this.empleado = empleado;
        pagoEfectivoText.setEnabled(false);

        String[] columnas = {"ID", "Título del Libro", "Precio", "Cantidad"};
        DefaultTableModel model = new DefaultTableModel(null, columnas);
        jTable1.setModel(model);
        
        nombreVendedor.setText(empleado.getNombre());
        apellidoPatVendedor.setText(empleado.getApePaterno());
        apellidoMatVendedor.setText(empleado.getApeMaterno());
        
        if (empleado instanceof Vendedor) {
            Vendedor vendedor = (Vendedor) empleado;
            ArrayList<Libro> listaDeCompra = vendedor.getListaDeCompra();
            ArrayList<Integer> arregloCantidades = vendedor.getCantidades();
            
            model.setRowCount(0);
            
            for (int i = 0; i < listaDeCompra.size(); i++) {
                Libro libro1 = listaDeCompra.get(i);
                int cantidad = arregloCantidades.get(i);
                total = (libro1.getPrecioLibro() - (libro1.getPrecioLibro()*libro1.getDescuento()))*cantidad;
                sumatoria = sumatoria + total;
                
                Object[] row = {libro1.getId(), libro1.getTituloLibro(), libro1.getPrecioLibro(), cantidad};
                model.addRow(row);
            }
        }
        
        totalStr.setText(Double.toString(sumatoria));
        
        if (empleado instanceof Vendedor) {
            tipoEmp = 1;
        } else if (empleado instanceof Almacenista) {
            tipoEmp = 2;
        } else if (empleado instanceof Admin) {
            tipoEmp = 3;
        }
        
        PointerInfo pointerInfo = MouseInfo.getPointerInfo();
        GraphicsDevice gd = pointerInfo.getDevice();
        Rectangle bounds = gd.getDefaultConfiguration().getBounds();

        // Obtener las dimensiones del formulario
        int frameWidth = 400;  // Ancho del formulario
        int frameHeight = 430; // Alto del formulario

        // Calcular las coordenadas para centrar el formulario
        int x = bounds.x + (bounds.width - frameWidth) / 2;
        int y = bounds.y + (bounds.height - frameHeight) / 2;

        //this.setSize(frameWidth, frameHeight);
        this.setLocation(x, y);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        
        Funciones.CargarLogo(lbl_logo);
    }
    
    public void actualizarTabla(ArrayList<Libro> libros) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

        for (Libro libro : libros) {
            Object[] fila = {libro.getId(), libro.getTituloLibro(), libro.getPrecioLibro()};
            model.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pagoEfectivoText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nombreVendedor = new javax.swing.JLabel();
        apellidoPatVendedor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalStr = new javax.swing.JLabel();
        apellidoMatVendedor = new javax.swing.JLabel();
        totalStr1 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jButtonPagoTarjeta = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        lbl_lista = new javax.swing.JLabel();
        pagoEfectivo = new javax.swing.JButton();
        lbl_logo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 136, 130));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pago con:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 113, -1));

        pagoEfectivoText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagoEfectivoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoEfectivoTextActionPerformed(evt);
            }
        });
        jPanel2.add(pagoEfectivoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 113, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Su cambio:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 113, -1));

        cambio.setBackground(new java.awt.Color(255, 255, 255));
        cambio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cambio.setForeground(new java.awt.Color(255, 255, 255));
        cambio.setText("$0");
        jPanel2.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 113, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 180, 150));

        jPanel3.setBackground(new java.awt.Color(211, 211, 211));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Vendedor:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 113, -1));

        nombreVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombreVendedor.setText("xxxxxxxxxx");
        jPanel3.add(nombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 113, -1));

        apellidoPatVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apellidoPatVendedor.setText("xxxxxxxxxx");
        jPanel3.add(apellidoPatVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Total a pagar:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 127, -1));

        totalStr.setBackground(new java.awt.Color(255, 255, 255));
        totalStr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalStr.setForeground(new java.awt.Color(209, 59, 83));
        totalStr.setText("100");
        jPanel3.add(totalStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 90, -1));

        apellidoMatVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apellidoMatVendedor.setText("xxxxxxxxxx");
        jPanel3.add(apellidoMatVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        totalStr1.setBackground(new java.awt.Color(255, 255, 255));
        totalStr1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalStr1.setForeground(new java.awt.Color(209, 59, 83));
        totalStr1.setText("$");
        jPanel3.add(totalStr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 20, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 150));

        jButtonRegresar.setBackground(new java.awt.Color(209, 59, 83));
        jButtonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 180, 40));

        jButtonPagoTarjeta.setBackground(new java.awt.Color(209, 59, 83));
        jButtonPagoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonPagoTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPagoTarjeta.setText("Pago con tarjeta");
        jButtonPagoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagoTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPagoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 180, 40));

        finalizar.setBackground(new java.awt.Color(209, 59, 83));
        finalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalizar.setForeground(new java.awt.Color(255, 255, 255));
        finalizar.setText("Pagar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        jPanel1.add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 180, 40));

        lbl_lista.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lbl_lista.setText("LISTA DE VENTA");
        jPanel1.add(lbl_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        pagoEfectivo.setBackground(new java.awt.Color(209, 59, 83));
        pagoEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagoEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        pagoEfectivo.setText("Pago con efectivo");
        pagoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoEfectivoActionPerformed(evt);
            }
        });
        jPanel1.add(pagoEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 180, 40));

        lbl_logo.setText("logo");
        lbl_logo.setToolTipText("");
        jPanel1.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        PuntoDeVenta puntoDeVenta = new PuntoDeVenta(empleado);
        puntoDeVenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonPagoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagoTarjetaActionPerformed
        new PagoTarjeta(ListaDeVenta.this).setVisible(true);
    }//GEN-LAST:event_jButtonPagoTarjetaActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        if(pagoEfectivoText.isEnabled()==true){  
            double cantidadIngresada = Double.parseDouble(pagoEfectivoText.getText());
            if(cantidadIngresada >= sumatoria){
                totalStr.setText("0");
                double cambio1 = cantidadIngresada - sumatoria;
                cambio.setText("$" + Double.toString(cambio1));

                String[] columnas = {"ID", "Título del Libro", "Precio", "Cantidad"};
                DefaultTableModel model = new DefaultTableModel(null, columnas);
                jTable1.setModel(model);

                if (empleado instanceof Vendedor) {
                    Vendedor vendedor = (Vendedor) empleado;
                    vendedor.limpiarListaDeCompra();
                    vendedor.limpiarArregloCantidades();
                    ArrayList<Libro> listaDeCompra = vendedor.getListaDeCompra();
                    ArrayList<Integer> arregloCantidades = vendedor.getCantidades();

                    model.setRowCount(0);

                    for (int i = 0; i < listaDeCompra.size(); i++) {
                        Libro libro1 = listaDeCompra.get(i);
                        int cantidad = arregloCantidades.get(i);
                        total = (libro1.getPrecioLibro() - (libro1.getPrecioLibro()*libro1.getDescuento()))*cantidad;
                        sumatoria = sumatoria + total;

                        Object[] row = {libro1.getId(), libro1.getTituloLibro(), libro1.getPrecioLibro(), cantidad};
                        model.addRow(row);
                    }
                    Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                    vendedor.registrarTransaccion(3, timestamp, sumatoria, 1, vendedor.getId(), 1);
                }

                pagoEfectivoText.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "La cantidad ingresadano es suficiente.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_finalizarActionPerformed

    private void pagoEfectivoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoEfectivoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagoEfectivoTextActionPerformed

    private void pagoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoEfectivoActionPerformed
        pagoEfectivoText.setEnabled(true);
    }//GEN-LAST:event_pagoEfectivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeVenta(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoMatVendedor;
    private javax.swing.JLabel apellidoPatVendedor;
    private javax.swing.JLabel cambio;
    private javax.swing.JButton finalizar;
    private javax.swing.JButton jButtonPagoTarjeta;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_lista;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel nombreVendedor;
    private javax.swing.JButton pagoEfectivo;
    public javax.swing.JTextField pagoEfectivoText;
    public javax.swing.JLabel totalStr;
    public javax.swing.JLabel totalStr1;
    // End of variables declaration//GEN-END:variables
}
